# find_path(COLLIER_INCLUDE_DIR NAMES zlib.h PATHS ${CONAN_INCLUDE_DIRS_COLLIER})
find_library(COLLIER_LIBRARY NAMES ${CONAN_LIBS_COLLIER} PATHS ${CONAN_LIB_DIRS_COLLIER})

set(COLLIER_FOUND TRUE)
set(COLLIER_INCLUDE_DIRS ${COLLIER_INCLUDE_DIR})
set(COLLIER_LIBRARIES ${COLLIER_LIBRARY})
mark_as_advanced(COLLIER_LIBRARY COLLIER_INCLUDE_DIR)
