find_library(COLLIER_LIBRARY NAMES ${CONAN_LIBS_COLLIER} PATHS ${CONAN_LIB_DIRS_COLLIER})

set(COLLIER_FOUND TRUE)
set(COLLIER_INCLUDE_DIRS ${COLLIER_INCLUDE_DIR})
set(COLLIER_LIBRARIES ${COLLIER_LIBRARY})
mark_as_advanced(COLLIER_LIBRARY COLLIER_INCLUDE_DIR)

if(COLLIER_FOUND AND NOT TARGET COLLIER::COLLIER)
  add_library(COLLIER::COLLIER UNKNOWN IMPORTED)
  set_target_properties(COLLIER::COLLIER PROPERTIES
    IMPORTED_LOCATION "${COLLIER_LIBRARIES}"
    INTERFACE_INCLUDE_DIRECTORIES "${COLLIER_INCLUDE_DIRS}"
  )
endif()
